function FPEX0_visualize(setup, sol)
% FPEX0_visualize(setup, sol)
%
% Visualizes a simulation sol generated by FPEX0_simulate.
%
% INPUT:   sol --> solution object (from Matlab integrator)
%        setup --> FPEX0_setup structure
%
% OUTPUT   none
%
% Author:  Andreas Sommer, Aug2022
% andreas.sommer@iwr.uni-heidelberg.de
% code@andreas-sommer.eu


% accessors
fignum = 337;
tgrid = setup.grid.gridTdot;
xgrid = setup.grid.gridT;
N = setup.grid.N;

% evaluation
u = deval(sol, tgrid);

% plot
figure(fignum);
clf; hold('on')
for i = 1:length(tgrid)
   tvec = tgrid(i) * ones(N,1);
   plot3(xgrid, tvec, u(:,i));
end
view([6,27])
ylabel('Heat rate \beta  (time t)')
xlabel('Temperature T   (space x)')
zlabel('c_p   (value u)')
grid('on')

end